@UserTaskAPI_HostAddress = https://localhost:4000

GET {{UserTaskAPI_HostAddress}}/api/users
Content-Type: application/json

###

POST {{UserTaskAPI_HostAddress}}/api/users
Content-Type: application/json

{

}

###

POST {{UserTaskAPI_HostAddress}}/api/users
Content-Type: application/json

{
    "birthday": "1985-11-01T00:00:00.000Z"
}

###

Put {{UserTaskAPI_HostAddress}}/api/users/6
Content-Type: application/json

{
    
}

###

POST {{UserTaskAPI_HostAddress}}/api/users
Content-Type: application/json

{
    "name": "Josh"
}

###

POST {{UserTaskAPI_HostAddress}}/api/users
Content-Type: application/json

{
    "id": 0,
    "name": "Rob",
    "birthday": "1990-09-14T00:00:00.000Z"
}

###

GET {{UserTaskAPI_HostAddress}}/api/user/3

###

DELETE {{UserTaskAPI_HostAddress}}/api/users/5

###


PUT {{UserTaskAPI_HostAddress}}/api/users/{{id}}
Content-Type: application/json

{
    "id": 3,
    "name": "Tonyyy",
    "birthday": "2001-11-01T00:00:00.000Z"
}

###

PATCH {{UserTaskAPI_HostAddress}}/api/users/3
Content-Type: application/json
{
    "birthday": "asd"
}

###

GET {{UserTaskAPI_HostAddress}}/api/tasks
Content-Type: application/json

###

POST {{UserTaskAPI_HostAddress}}/api/tasks
Content-Type: application/json

{
  "userid": 1
}

###

POST {{UserTaskAPI_HostAddress}}/api/tasks
Content-Type: application/json

{
    "userId": 6
}

###

GET {{UserTaskAPI_HostAddress}}/api/tasks

###

DELETE {{UserTaskAPI_HostAddress}}/api/tasks/5

###

PUT {{UserTaskAPI_HostAddress}}/api/tasks/2
Content-Type: application/json
{
  
}

###

PATCH {{UserTaskAPI_HostAddress}}/api/tasks/2
Content-Type: application/json
{
  "Description":"Deploy and Test API."
}